### ISSUE TITLE
Error: Connection lost: The server closed the connection

### ISSUE THREAD

**Issue by SteveIM1980** [Viokeoke/ejemplo-de-api-con-nodejs-express-y-mysql#1]
Hola Viokeoke,
Muchas gracias por el ejemplo, me ha sido muy útil.

Tengo una pregunta respecto a la conexión de la BD. Cada vez que ejecuto una query al rato pierdo la conexion usando el comando "node app.js". Para reconectar automáticamente uso Forever js.
Mi pregunta es, si es posible evitar perder la conexion a la BD?
Abajo el error.
Gracias.
Steve.

Error: Connection lost: The server closed the connection.
    at Protocol.end (/aplicaciones/MiscondolenciasServicios/node_modules/mysql/lib/protocol/Protocol.js:109:13)
    at Socket.<anonymous> (/aplicaciones/MiscondolenciasServicios/node_modules/mysql/lib/Connection.js:115:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error: Forever detected script exited with code: 1
error: Script restart attempt #94
Servidor iniciado ok..

**Comment by Viokeoke** [comment]
la verdad es que es un error raro, ¿podrías ampliar la información que te devuelve la consola o dejarme la query que hace que te deje de funcionar?
